brews:
  -
    tap:
      owner: Envoy49
      name: homebrew-go-spotify-cli
    commit_author:
      name: goreleaserbot
      email: goreleaser@bot.com
    folder: Formula
    homepage: "https://github.com/Envoy49/go-spotify-cli"
    description: "A CLI for Spotify"
